# -*- coding: utf-8 -*-
"""01. Algoritmo de escada

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vNJuTZx21QSEDWEtwoIgz6JsBbqRN46r
"""

#Av1 Modelagem paramétrica e simulações digitais

# equipe:
# 1- Gabriela Gusmão
# 2- Gabriele Melo
# 3- Maria Eduarda Britto
# 4- Rute Robatto
# 5- Sofia Santana

#docente - Fernando Ribeiro

# importando função ceil
import math

# entrada de dados de distância por pavimento
dist = input ("Entre com a distância entre pavimentos\n")

# transformando o valor em float
dist= float (dist)

# lendo o valor da altura máxima dos espelhos e transformando em float
h_max= float(input ("Entre com o valor máximo de espelho\n"))

print (type(dist), type(h_max))

valor_01 = dist / h_max
print (valor_01)

# arredondando para o menor inteiro e maior ou igual a valor_01
num_esp = math.ceil(valor_01)

# calculando a altura dos espelhos
print ("numero de espelhos: ",num_esp)

h = dist / num_esp
print("Altura dos espelhos: ", h)

# formula de blondel fórmula é usada para calcular as medidas ideias para um piso de escada
p = .64 - 2*h

print ("produndidade do piso: ",p)