# -*- coding: utf-8 -*-
"""02. Algoritimo das cotas dos pavimentos - por altura máxima.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17h4xm7dWDiC0sv4iucLZPder0hWl31DP
"""

#Av1 Modelagem paramétrica e simulações digitais

# equipe:
# 1- Gabriela Gusmão
# 2- Gabriele Melo
# 3- Maria Eduarda Britto
# 4- Rute Robatto
# 5- Sofia Santana

#docente - Fernando Ribeiro

# definição das variáveis
cota_piso = float (input("entre com a cota do terreno"))
pap = float (input("entre com a distância piso a piso"))
cota_max = float (input("entre com o valor máximo de altura"))

#condição para saber se a cota do nível atual está abaixo do nível máximo
count = 0
while cota_piso <= cota_max:
#contador para saber a quantidade total de andares
   count = count + 1
   print(cota_piso)
   cota_piso = cota_piso + pap
print("total de pisos:", count)