# -*- coding: utf-8 -*-
"""malha_de_pilares_2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fYBbMUKc4kSiORmkhcktymUm7WtoSZv6
"""

#Av1 Modelagem paramétrica e simulações digitais

# Equipe:
# 1- Gabriela Gusmão
# 2- Gabriele Melo
# 3- Maria Eduarda Britto
# 4- Rute Robatto
# 5- Sofia Santana

#Docente - Fernando Ribeiro

#importando bibliotecas
import numpy as np #biblioteca de matemática
import matplotlib.pyplot as plt #biblioteca para gerar gráficos e figuras

#arange aceita valores quebrados
x = np.arange(-10, 10, .25)
x

#plotagem da figura de sen x
plt.plot(np.sin(x))

#plotagem da figura com pontos
fig ,ax= plt.subplots()
ax.plot(x,np.sin(x)) #plotagem da figura com um só eixo
ax.scatter(x,np.sin(x), c='red') #plotagem dos pontos, escolha da cor dos pontos

#entradas de valores
nx = 8
dx = 20
ny = 12
dy = 10

#criação de listas vazias
coord_x = []
coord_y = []

#utilizar for para gerar uma série de valores cada vez que for rodado
for i in range(nx):
  for j in range(ny): #um for dentro do outra para criar uma segunda dimensão
    #append para adicionar valores na lista
    coord_x.append(i*dx)
    coord_y.append(j*dy)

#plotagem dos valores gerados nas listas
print("x: ", coord_x)
print("y: ", coord_y)

#plotagem de pontos nas coordenadas
fig, ax = plt.subplots()
ax.scatter(coord_x, coord_y) #plotagem dos pontos
ax.set_aspect('equal') #manter a proporção entre os eixos x e y
plt.title("Malha regular de pilares") #inserir um título na imagem