# -*- coding: utf-8 -*-
"""malha_de_pilares_25.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152pfoF39PIht7FcJy_0GgAs4CkTkk7RH
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.arange(-10, 11, .25)
x

plt.plot(np.sin(x))

fig = plt.figure(figsize = (10,10))

plt.plot(np.sin(x))

fig ,ax= plt.subplots()
ax.plot(x, np.sin (x))
ax.scatter(x, np.sin (x), c='red')

nx = 6
dx = 10
ny = 8
dy = 10

coord_x = []
coord_y = []
for i in range(nx):
  for j in range(ny):
    coord_x.append(i*dx)
    coord_y.append(j*dy)

print("coordenadas", coord_x)
print("coordenadas", coord_y)

fig, ax = plt.subplots()
ax.scatter(coord_x, coord_y)
#ax.set_aspect('equal')
plt.title("MALHA REGULAR")