# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZgyUKHL8texqKqOVeyHVGoUBHzP3k4p
"""

import numpy as np
import matplotlib.pyplot as plt

# entradas
comp = 10.0 #Float
h = 2.0 # Float
n_nos = 10 #int

coord_x = np.linspace(0, comp, n_nos)
coord_y1 = [0]* n_nos
coord_y2 = [h]* n_nos

diag_y = []
for i in range (n_nos):
  if i % 2 == 0:
    diag_y.append(0)
  else:
    diag_y.append(h)
print(diag_y)

fig, ax = plt.subplots ()
ax.set_title("Treliça Av1")
ax.scatter(coord_x,coord_y1)
ax.plot(coord_x,coord_y1)
ax.scatter(coord_x,coord_y2)
ax.plot(coord_x,coord_y2)
ax.plot(coord_x, diag_y)
ax.set_aspect("equal")
plt.show()


