# -*- coding: utf-8 -*-
"""03. Algoritmo das cotas dos pavimentos - por número de pavimentos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yBgPiDINTkDLYIpe0KRUy6sBGHG9ktWt
"""

#Av1 Modelagem paramétrica e simulações digitais

# equipe:
# 1- Gabriela Gusmão
# 2- Gabriele Melo
# 3- Maria Eduarda Britto
# 4- Rute Robatto
# 5- Sofia Santana

#docente - Fernando Ribeiro

# Definindo o valor inicial da cota e transformando para float
cota_init = float(input("valor da cota inicial\n"))

# Definindo o valor do numero de paviemnto
n_pav = int(input("valor da cota inicial\n"))

# Definindo o valor da distância de piso a piso
pap = float(input("valor da cota inicial\n"))

# Definindo o comprimento de cotas e organizando eles por lista com uma lista vazia e o append
cotas = []
for i in range(n_pav):
  cotas.append(cota_init + (i * pap))
  print(len(cotas))
  print(cotas)

